# Assessment Problems

## Problem 1: Data from yfinance

Using the yfinance Python package, write a function called get_data() that downloads all hourly data for the previous five days for the five FAANG stocks:


    Facebook (META)
    Apple (AAPL)
    Amazon (AMZN)
    Netflix (NFLX)
    Google (GOOG)

The function should save the data into a folder called data in the root of your repository using a filename with the format YYYYMMDD-HHmmss.csv where YYYYMMDD is the four-digit year (e.g. 2025), followed by the two-digit month (e.g. 09 for September), followed by the two digit day, and HHmmss is hour, minutes, seconds. Create the data folder if you don't already have one.

## Problem 1. Answer

First step is to import the yfinance python package so we can then access the stock data for the five FAANG stocks and the yfinance functions. Pandas should be included in the yfinance import but I will import anyway. Will also import datetime as it will be required later in the question.

In [28]:

# dates and times
import datetime as dt


# data frame , pulled in with yfinance anyway 
import pandas as pd

# import yahoo finance data
import yfinance as yf

Next step is to get the stock data required for for each tickers-Facebook(META),Google(GOOG),Apple(AAPL),Amazon(AMZN)
and Netlix(NFLX).

(A ticker is a shortened name for thhe company stock eg. MSFT for microsoft)

Reference: https://ranaroussi.github.io/yfinance/reference/api/yfinance.download.html

In [29]:
# Example of how to get the data for one ticker
# dat = yf.Ticker("MSFT")

# for multiple tickers , with spaces to seperate each
Tickers = yf.Tickers('META AAPL GOOG AMZN NFLX')

In [30]:
# to download the data 
# use the download function in yfinance, can also test the period function here to check the data
yf.download(['META', 'AAPL', 'GOOG', 'AMZN', 'NFLX'], period='5d')
# info from below link other examples of periods are eg. 1d,5d,1mo,3mo,6mo,1y,2y,5y,
# https://ranaroussi.github.io/yfinance/reference/api/yfinance.download.html

/tmp/ipykernel_43318/2216655638.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(['META', 'AAPL', 'GOOG', 'AMZN', 'NFLX'], period='5d')
[*********************100%***********************]  5 of 5 completed

Price            Close                                                 \
Ticker            AAPL        AMZN        GOOG        META       NFLX
Date
2025-12-08  277.890015  226.889999  314.450012  666.799988  96.790001
2025-12-09  277.179993  227.919998  317.750000  656.960022  96.709999
2025-12-10  278.779999  231.779999  321.000000  650.130005  92.709999
2025-12-11  278.029999  230.279999  313.700012  652.710022  94.089996
2025-12-12  278.279999  226.190002  310.519989  644.229980  95.190002

Price             High                                                 ...  \
Ticker            AAPL        AMZN        GOOG        META       NFLX  ...
Date                                                                   ...
2025-12-08  279.670013  230.830002  321.230011  676.710022  99.889999  ...
2025-12-09  280.029999  228.570007  318.709015  664.479980  97.239998  ...
2025-12-10  279.750000  232.419998  321.869995  654.510010  96.970001  ...
2025-12-11  279.589996  232.110001  321.989990  655.280029  94.820000  ...
2025-12-12  279.220001  230.080002  316.130005  711.000000  96.919998  ...

Price             Open                                                 \
Ticker            AAPL        AMZN        GOOG        META       NFLX
Date
2025-12-08  278.130005  229.589996  321.029999  669.340027  99.870003
2025-12-09  278.160004  226.839996  313.100006  663.770020  97.029999
2025-12-10  277.750000  228.809998  316.619995  649.950012  96.739998
2025-12-11  279.100006  230.710007  321.100006  643.289978  93.900002
2025-12-12  277.795013  230.020004  314.809998  650.210022  95.504997

Price         Volume
Ticker          AAPL      AMZN      GOOG      META       NFLX
Date
2025-12-08  38211800  35019200  22006900  13161000  100906300
2025-12-09  32193300  25841700  14151300  12997100   51745600
2025-12-10  33038300  38790700  22764500  16910900   74129300
2025-12-11  33248000  28249600  25912100  13056700   43949000
2025-12-12  38360082  33011277  20315069  12892636   43385562

[5 rows x 25 columns]

In [31]:
# now to add in the interval required which is every hour 
# interval will be '1h'

# get the data 
df = yf.download(['AAPL', 'MSFT', 'GOOG'], period='5d', interval='1h')

# check and see if correct
df

/tmp/ipykernel_43318/3615767356.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(['AAPL', 'MSFT', 'GOOG'], period='5d', interval='1h')
[*********************100%***********************]  3 of 3 completed

Price                           Close                                High  \
Ticker                           AAPL        GOOG        MSFT        AAPL
Datetime
2025-12-08 14:30:00+00:00  277.559998  317.950012  489.077209  279.669312
2025-12-08 15:30:00+00:00  277.459991  315.869385  491.489990  277.880005
2025-12-08 16:30:00+00:00  277.230011  313.019989  490.640015  277.819000
2025-12-08 17:30:00+00:00  276.970001  312.832397  490.890503  277.849915
2025-12-08 18:30:00+00:00  276.359985  313.609985  490.390015  276.949493
2025-12-08 19:30:00+00:00  276.924988  313.269989  489.894989  276.970001
2025-12-08 20:30:00+00:00  277.959991  314.290009  491.119995  277.984985
2025-12-09 14:30:00+00:00  277.700012  314.142487  490.470001  280.029999
2025-12-09 15:30:00+00:00  277.410004  314.619995  490.720001  278.000000
2025-12-09 16:30:00+00:00  277.875000  317.630798  489.950012  278.119995
2025-12-09 17:30:00+00:00  278.385010  318.670013  490.380005  278.739990
2025-12-09 18:30:00+00:00  278.690002  318.279999  490.890015  278.890015
2025-12-09 19:30:00+00:00  277.864990  317.920013  490.954987  278.750000
2025-12-09 20:30:00+00:00  277.230011  317.790009  492.059998  278.250000
2025-12-10 14:30:00+00:00  277.450012  318.739990  480.390015  278.792999
2025-12-10 15:30:00+00:00  278.257690  318.600006  480.364990  278.279999
2025-12-10 16:30:00+00:00  278.526489  317.075104  481.600006  278.890015
2025-12-10 17:30:00+00:00  278.119995  316.700012  477.290009  279.279999
2025-12-10 18:30:00+00:00  278.220001  318.609985  476.470001  279.220001
2025-12-10 19:30:00+00:00  278.980011  320.510010  478.059998  279.750000
2025-12-10 20:30:00+00:00  278.720001  320.850006  478.521515  279.369995
2025-12-11 14:30:00+00:00  276.119995  317.059998  480.350006  279.579987
2025-12-11 15:30:00+00:00  275.825012  315.549988  478.951904  276.589996
2025-12-11 16:30:00+00:00  277.904999  316.059998  480.666809  278.179993
2025-12-11 17:30:00+00:00  277.522614  313.390015  482.010010  278.350006
2025-12-11 18:30:00+00:00  277.760010  313.605011  485.450012  278.209991
2025-12-11 19:30:00+00:00  278.095001  313.350006  484.380005  278.214996
2025-12-11 20:30:00+00:00  278.059998  313.709991  483.690002  278.209991
2025-12-12 14:30:00+00:00  277.869995  309.589996  478.445007  279.220001
2025-12-12 15:30:00+00:00  277.739990  308.000000  477.768494  278.859985
2025-12-12 16:30:00+00:00  277.855011  309.570007  477.765015  278.440002
2025-12-12 17:30:00+00:00  279.049988  311.649994  478.829987  279.190002
2025-12-12 18:30:00+00:00  277.950012  310.962799  478.950104  279.049988
2025-12-12 19:30:00+00:00  278.054993  310.799988  478.255005  278.700012
2025-12-12 20:30:00+00:00  278.369995  310.510010  478.470001  278.500000

Price                                                     Low              \
Ticker                           GOOG        MSFT        AAPL        GOOG
Datetime
2025-12-08 14:30:00+00:00  321.230011  490.619995  277.450012  317.660004
2025-12-08 15:30:00+00:00  317.899994  492.299988  276.704987  315.619995
2025-12-08 16:30:00+00:00  316.160004  491.640015  277.000092  311.910004
2025-12-08 17:30:00+00:00  313.989990  492.059998  276.869995  312.190002
2025-12-08 18:30:00+00:00  314.269897  491.047485  276.200012  312.704987
2025-12-08 19:30:00+00:00  314.065002  490.359985  276.149994  312.839996
2025-12-08 20:30:00+00:00  314.570007  491.200012  276.660004  312.640015
2025-12-09 14:30:00+00:00  314.571503  491.940002  277.350006  312.619995
2025-12-09 15:30:00+00:00  315.269989  491.130005  277.029999  313.540009
2025-12-09 16:30:00+00:00  317.679993  492.100006  277.200012  314.459991
2025-12-09 17:30:00+00:00  318.708893  490.489990  277.799988  317.329987
2025-12-09 18:30:00+00:00  318.700012  491.190002  278.119995  317.710114
2025-12-09 19:30:00+00:00  318.475006  491.369995  277.649994  317.586487
2025-12-09 20:30:00+00:00  318.019989  492.100006  276.920013  314.450012
2025-12-10 14:30:00+00:00  319.519989  484.250000  276.584991  315.399994
2025-12-10 15:30:00+00:00  318.859589  480.600006  276.440002  317.359985
2025-12-10 16:30:00+00:00  318.825012  481.769989  277.975006  317.070007
2025-12-10 17:30:00+00:00  318.029510  482.412109  278.084991  316.688812
2025-12-10 18:30:00+00:00  319.600006  479.190002  277.910004  316.450012
2025-12-10 19:30:00+00:00  320.850006  479.649994  277.700012  318.179993
2025-12-10 20:30:00+00:00  321.869995  479.440002  278.589996  320.489990
2025-12-11 14:30:00+00:00  321.989990  482.140015  273.809998  314.519989
2025-12-11 15:30:00+00:00  317.890015  481.220001  275.200012  315.239990
2025-12-11 16:30:00+00:00  316.540009  481.535004  275.809998  314.660004
2025-12-11 17:30:00+00:00  316.543213  484.329987  277.380005  309.880005
2025-12-11 18:30:00+00:00  314.559998  486.029999  277.510010  311.234985
2025-12-11 19:30:00+00:00  314.299988  485.749908  277.591309  312.839996
2025-12-11 20:30:00+00:00  314.109985  484.394989  277.470001  312.850098
2025-12-12 14:30:00+00:00  316.130005  482.450012  276.820007  309.433014
2025-12-12 15:30:00+00:00  310.940002  480.600006  277.440002  307.088013
2025-12-12 16:30:00+00:00  310.779999  478.720001  277.280792  306.959991
2025-12-12 17:30:00+00:00  311.690002  479.420013  277.834991  309.019989
2025-12-12 18:30:00+00:00  311.890015  479.415009  277.730011  310.390015
2025-12-12 19:30:00+00:00  311.420013  479.290009  277.809998  310.570007
2025-12-12 20:30:00+00:00  310.929993  478.950012  276.945007  309.500000

Price                                        Open                          \
Ticker                           MSFT        AAPL        GOOG        MSFT
Datetime
2025-12-08 14:30:00+00:00  484.380005  278.168488  320.880005  484.885010
2025-12-08 15:30:00+00:00  488.390015  277.549988  317.899994  489.075012
2025-12-08 16:30:00+00:00  490.519989  277.470001  315.820099  491.529999
2025-12-08 17:30:00+00:00  490.100006  277.209991  313.043610  490.656006
2025-12-08 18:30:00+00:00  489.380096  276.949493  312.859985  490.809998
2025-12-08 19:30:00+00:00  489.311707  276.369995  313.595001  490.359985
2025-12-08 20:30:00+00:00  488.970001  276.929993  313.265015  489.890015
2025-12-09 14:30:00+00:00  488.500092  277.890015  314.450012  491.019989
2025-12-09 15:30:00+00:00  489.839996  277.700012  314.142487  490.470001
2025-12-09 16:30:00+00:00  489.950012  277.410004  314.640015  490.720001
2025-12-09 17:30:00+00:00  489.500000  277.875000  317.630798  489.980011
2025-12-09 18:30:00+00:00  490.220001  278.385010  318.670013  490.380005
2025-12-09 19:30:00+00:00  489.980011  278.690002  318.279999  490.890015
2025-12-09 20:30:00+00:00  490.820007  277.864990  317.920013  490.954987
2025-12-10 14:30:00+00:00  478.609985  277.869995  316.619995  484.029999
2025-12-10 15:30:00+00:00  478.089996  277.454987  318.700012  480.399994
2025-12-10 16:30:00+00:00  480.109985  278.230011  318.570007  480.399994
2025-12-10 17:30:00+00:00  476.850006  278.519989  317.040009  481.600006
2025-12-10 18:30:00+00:00  476.040009  278.119995  316.649994  477.279999
2025-12-10 19:30:00+00:00  475.079987  278.220001  318.679993  476.473297
2025-12-10 20:30:00+00:00  476.649994  278.989990  320.559998  478.109985
2025-12-11 14:30:00+00:00  475.859985  279.095001  320.940002  476.559998
2025-12-11 15:30:00+00:00  478.929993  276.114990  317.075012  480.385010
2025-12-11 16:30:00+00:00  478.920013  275.820007  315.524994  478.950012
2025-12-11 17:30:00+00:00  479.799988  277.920013  316.057495  480.700012
2025-12-11 18:30:00+00:00  481.530090  277.524994  313.410004  482.035004
2025-12-11 19:30:00+00:00  484.299988  277.760010  313.630005  485.464996
2025-12-11 20:30:00+00:00  482.323608  278.089996  313.339996  484.394989
2025-12-12 14:30:00+00:00  478.329987  277.795013  314.809998  479.820007
2025-12-12 15:30:00+00:00  476.359985  277.880005  309.609985  478.440002
2025-12-12 16:30:00+00:00  476.839996  277.769989  308.000000  477.690002
2025-12-12 17:30:00+00:00  477.170013  277.834991  309.570007  477.760010
2025-12-12 18:30:00+00:00  478.230011  279.040009  311.649994  478.850006
2025-12-12 19:30:00+00:00  477.769989  277.950012  310.970001  478.980011
2025-12-12 20:30:00+00:00  477.350006  278.049988  310.820007  478.250000

Price                       Volume
Ticker                        AAPL     GOOG     MSFT
Datetime
2025-12-08 14:30:00+00:00  6285926  3758988  3442595
2025-12-08 15:30:00+00:00  3326326  2078465  1631887
2025-12-08 16:30:00+00:00  1896481  2665657  1057622
2025-12-08 17:30:00+00:00  1999024  1384447  1131610
2025-12-08 18:30:00+00:00  1825108  1098322   857571
2025-12-08 19:30:00+00:00  2861661  1012658  1078837
2025-12-08 20:30:00+00:00  2613900  6086234  1521777
2025-12-09 14:30:00+00:00  5341504  2063287  2206572
2025-12-09 15:30:00+00:00  2290151  1009941   858330
2025-12-09 16:30:00+00:00  1696929  1191496   760850
2025-12-09 17:30:00+00:00  1988455  1262633   958263
2025-12-09 18:30:00+00:00  1262893   629339   527622
2025-12-09 19:30:00+00:00  1906538   764080   671392
2025-12-09 20:30:00+00:00  2737573  1170453  3546772
2025-12-10 14:30:00+00:00  3868165  2497344  4407586
2025-12-10 15:30:00+00:00  1880040   887438  2242212
2025-12-10 16:30:00+00:00  1611918   900377  1205981
2025-12-10 17:30:00+00:00  1374275   711869  2257500
2025-12-10 18:30:00+00:00  1631790  1057225  2388387
2025-12-10 19:30:00+00:00  2578278  1555562  3137199
2025-12-10 20:30:00+00:00  2242651  1865336  3156115
2025-12-11 14:30:00+00:00  6887208  3634473  3902934
2025-12-11 15:30:00+00:00  2343607  1521142  1387331
2025-12-11 16:30:00+00:00  2412367  1109293  1074923
2025-12-11 17:30:00+00:00  1473658  2408094  1680983
2025-12-11 18:30:00+00:00  1432317  2208647  1967481
2025-12-11 19:30:00+00:00  1817634  1218542  1089784
2025-12-11 20:30:00+00:00  1985352  1611593  1534951
2025-12-12 14:30:00+00:00  3907328  3133641  3170937
2025-12-12 15:30:00+00:00  3485545  2344376  2058673
2025-12-12 16:30:00+00:00  2096132  1633867  1289724
2025-12-12 17:30:00+00:00  2564725  1082515  1111781
2025-12-12 18:30:00+00:00  2354465   809271   764406
2025-12-12 19:30:00+00:00  2391168   722659  1011975
2025-12-12 20:30:00+00:00  2787871  1398728  1603990

now that the required data is downloaded we need to save it to a data folder
but first we must format the df to a csv and the name to a date and time required using datetime functions

imported above

reference : https://docs.python.org/3/library/datetime.html
reference : https://www.w3schools.com/python/python_datetime.asp
refernece : https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

In [ ]:
# csv to data folder
# this is how to save the df to a csv file in data folder 

# df.to_csv('data/data.csv')

# but first we must format the date time name as below

In [ ]:
## file name and datetime set up 

# below function found on https://docs.python.org/3/library/datetime.html and explained in Ian McLoughlin video lectures.

# now.straftime will output a string 
# ("%Y%m%d %H%M%S") is the format of the string output in (yearmonthdate hourminutesecond)
# can add spaces but neater and shorter like this
# and csv is the extension

# now.strftime("%Y%m%d %H%M%S") + ".csv"


# command (folder + file + extension)
# df.to_csv("data/" + now.strftime("%Y%m%d %H%M%S") + ".csv")

# if above one is run again it will OVERRIGHT the current file in data folder with new information


# change now.strftime function to dt.datetime.now() 
# will save different file each time , with time stamp for name 
df.to_csv("data/" + dt.datetime.now().strftime("%Y%m%d %H%M%S") + ".csv")

## Problem 2: Plotting Data
Write a function called plot_data() that opens the latest data file in the data folder and, on one plot, plots the Close prices for each of the five stocks. The plot should include axis labels, a legend, and the date as a title. The function should save the plot into a plots folder in the root of your repository using a filename in the format YYYYMMDD-HHmmss.png. Create the plots folder if you don't already have one.

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html

## Problem 3: Script
Create a Python script called faang.py in the root of your repository. Copy the above functions into it and make it so that whenever someone at the terminal types ./faang.py, the script runs, downloading the data and creating the plot. Note that this will require a shebang line and the script to be marked executable. Explain the steps you took in your notebook.

## Problem 4: Automation
Create a GitHub Actions workflow to run your script every Saturday morning. The script should be called faang.yml in a .github/workflows/ folder in the root of your repository. In your notebook, explain each of the individual lines in your workflow.