In [ ]:
import yfinance as yf

dat = yf.Ticker("MSFT")

yfinance.Ticker object <MSFT>

In [4]:
dat.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "Microsoft Corporation develops and supports software, services, devices, and solutions worldwide. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Windows Commercial, Power BI, Exchange, SharePoint, Microsoft Teams, Security and Compliance, and Copilot; Microsoft 365 Commercial products, such as Windows Commercial on-premises and Office licensed services; Microsoft 365 Consumer products and cloud services, such as Microsoft 365 Consumer subscriptions, Office licensed on-premises, and other consumer services; LinkedIn; Dynamics products and cloud services, such as Dynamics 365, cloud-based applications, and on-premises ERP and CRM applications. Its Intelligent Cloud segment provides Server products and cloud services, such as Azure and other cloud services, GitHub, Nuance Healthcare, virtual desktop offerings, and other cloud services; Server products, including SQL and Windows Server, Visual Studio and System Center related Client Access Licenses, and other on-premises offerings; Enterprise and partner services, including Enterprise Support and Nuance professional Services, Industry Solutions, Microsoft Partner Network, and Learning Experience. The company's Personal Computing segment provides Windows and Devices, such as Windows OEM licensing and Devices and Surface and PC accessories; Gaming services and solutions, such as Xbox hardware, content, and services, first- and third-party content Xbox Game Pass, subscriptions, and Cloud Gaming, advertising, and other cloud services; search and news advertising services, such as Bing and Copilot, Microsoft News and Edge, and third-party affiliates. It sells its products through OEMs, distributors, and resellers; and online and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'fullTimeEmployees': 228000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 57,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 65,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 52,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 53,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 51,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1973,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 52,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 58,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 8,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1764547200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 478.324,
 'open': 476.56,
 'dayLow': 475.86,
 'dayHigh': 486.03,
 'regularMarketPreviousClose': 478.324,
 'regularMarketOpen': 476.56,
 'regularMarketDayLow': 475.86,
 'regularMarketDayHigh': 486.03,
 'dividendRate': 3.64,
 'dividendYield': 0.76,
 'exDividendDate': 1771459200,
 'payoutRatio': 0.2361,
 'fiveYearAvgDividendYield': 0.8,
 'beta': 1.07,
 'trailingPE': 34.023224,
 'forwardPE': 25.81777,
 'volume': 23182196,
 'regularMarketVolume': 23182196,
 'averageVolume': 22457268,
 'averageVolume10days': 23451860,
 'averageDailyVolume10Day': 23558270,
 'bid': 477.68,
 'ask': 483.84,
 'bidSize': 1,
 'askSize': 2,
 'marketCap': 3593712959488,
 'fiftyTwoWeekLow': 344.79,
 'fiftyTwoWeekHigh': 555.45,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'priceToSalesTrailing12Months': 12.231335,
 'fiftyDayAverage': 506.1384,
 'twoHundredDayAverage': 471.04996,
 'trailingAnnualDividendRate': 3.4,
 'trailingAnnualDividendYield': 0.007108153,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3611694727168,
 'profitMargins': 0.35707,
 'floatShares': 7421526384,
 'sharesOutstanding': 7432377655,
 'sharesShort': 61948927,
 'sharesShortPriorMonth': 52549516,
 'sharesShortPreviousMonthDate': 1761868800,
 'dateShortInterest': 1764288000,
 'sharesPercentSharesOut': 0.0083,
 'heldPercentInsiders': 0.00067000004,
 'heldPercentInstitutions': 0.75723,
 'shortRatio': 2.3,
 'shortPercentOfFloat': 0.0083,
 'impliedSharesOutstanding': 7433166379,
 'bookValue': 48.84,
 'priceToBook': 9.899058,
 'lastFiscalYearEnd': 1751241600,
 'nextFiscalYearEnd': 1782777600,
 'mostRecentQuarter': 1759190400,
 'earningsQuarterlyGrowth': 0.125,
 'netIncomeToCommon': 104912003072,
 'trailingEps': 14.21,
 'forwardEps': 18.72625,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 12.293,
 'enterpriseToEbitda': 21.7,
 '52WeekChange': 0.08093548,
 'SandP52WeekChange': 0.14045572,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1763596800,
 'quoteType': 'EQUITY',
 'currentPrice': 483.47,
 'targetHighPrice': 730.0,
 'targetLowPrice': 483.0,
 'targetMeanPrice': 625.4096,
 'targetMedianPrice': 634.15,
 'recommendationMean': 1.28571,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 52,
 'totalCash': 102012002304,
 'totalCashPerShare': 13.725,
 'ebitda': 166436995072,
 'totalDebt': 120375001088,
 'quickRatio': 1.254,
 'currentRatio': 1.401,
 'totalRevenue': 293812011008,
 'debtToEquity': 33.154,
 'revenuePerShare': 39.528,
 'returnOnAssets': 0.14656,
 'returnOnEquity': 0.32241002,
 'grossProfits': 202037002240,
 'freeCashflow': 53327376384,
 'operatingCashflow': 147038994432,
 'earningsGrowth': 0.127,
 'revenueGrowth': 0.184,
 'grossMargins': 0.68764,
 'ebitdaMargins': 0.56646997,
 'operatingMargins': 0.48873,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'priceEpsCurrentYear': 29.788132,
 'fiftyDayAverageChange': -22.668396,
 'fiftyDayAverageChangePercent': -0.044786952,
 'twoHundredDayAverageChange': 12.420044,
 'twoHundredDayAverageChangePercent': 0.026366724,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'gmtOffSetMilliseconds': -18000000,
 'market': 'us_market',
 'esgPopulated': False,
 'marketState': 'POSTPOST',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'postMarketChangePercent': 0.05346431,
 'postMarketPrice': 483.7285,
 'postMarketChange': 0.2584839,
 'regularMarketChange': 5.146,
 'regularMarketDayRange': '475.86 - 486.03',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 22421982,
 'fiftyTwoWeekLowChange': 138.68,
 'fiftyTwoWeekLowChangePercent': 0.4022158,
 'fiftyTwoWeekRange': '344.79 - 555.45',
 'fiftyTwoWeekHighChange': -71.98001,
 'fiftyTwoWeekHighChangePercent': -0.12958863,
 'fiftyTwoWeekChangePercent': 6.9957733,
 'dividendDate': 1773273600,
 'earningsTimestamp': 1761768000,
 'earningsTimestampStart': 1769634000,
 'earningsTimestampEnd': 1769634000,
 'earningsCallTimestampStart': 1761773400,
 'earningsCallTimestampEnd': 1761773400,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 14.21,
 'epsForward': 18.72625,
 'epsCurrentYear': 16.23029,
 'regularMarketChangePercent': 1.07584,
 'regularMarketPrice': 483.47,
 'corporateActions': [],
 'postMarketTime': 1765501197,
 'regularMarketTime': 1765486802,
 'exchange': 'NMS',
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.9764}

In [5]:
dat.calendar

{'Dividend Date': datetime.date(2026, 3, 12),
 'Ex-Dividend Date': datetime.date(2026, 2, 19),
 'Earnings Date': [datetime.date(2026, 1, 28)],
 'Earnings High': 4.11521,
 'Earnings Low': 3.56,
 'Earnings Average': 3.90766,
 'Revenue High': 81661025500,
 'Revenue Low': 78581000000,
 'Revenue Average': 80277350800}

In [6]:
dat.analyst_price_targets

{'current': 483.47,
 'high': 730.0,
 'low': 483.0,
 'mean': 625.4096,
 'median': 634.15}

In [7]:
dat.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-11-12 00:00:00-05:00,508.408446,510.714159,498.187585,510.185150,26574900,0.00,0.0
2025-11-13 00:00:00-05:00,509.356667,512.540710,500.353529,502.349792,25273100,0.00,0.0
2025-11-14 00:00:00-05:00,497.299241,510.644259,496.510708,509.226898,28505700,0.00,0.0
2025-11-17 00:00:00-05:00,507.500160,511.163287,503.966764,506.541931,19092800,0.00,0.0
2025-11-18 00:00:00-05:00,494.444589,502.040388,485.870639,492.867554,33815100,0.00,0.0
2025-11-19 00:00:00-05:00,489.184435,494.264923,481.927997,486.209991,23245300,0.00,0.0
2025-11-20 00:00:00-05:00,492.709991,493.570007,475.500000,478.429993,26802500,0.91,0.0
2025-11-21 00:00:00-05:00,478.500000,478.920013,468.269989,472.119995,31769200,0.00,0.0
2025-11-24 00:00:00-05:00,475.000000,476.899994,468.019989,474.000000,34421000,0.00,0.0
2025-11-25 00:00:00-05:00,474.070007,479.149994,464.890015,476.989990,28019800,0.00,0.0
2025-11-26 00:00:00-05:00,486.309998,488.309998,481.200012,485.500000,25709100,0.00,0.0
2025-11-28 00:00:00-05:00,487.600006,492.630005,486.649994,492.010010,14386700,0.00,0.0
2025-12-01 00:00:00-05:00,488.440002,489.859985,484.649994,486.739990,23964000,0.00,0.0
2025-12-02 00:00:00-05:00,486.720001,493.500000,486.320007,490.000000,19562700,0.00,0.0
2025-12-03 00:00:00-05:00,476.320007,484.239990,475.200012,477.730011,34615100,0.00,0.0
2025-12-04 00:00:00-05:00,479.760010,481.320007,476.489990,480.839996,22318200,0.00,0.0
2025-12-05 00:00:00-05:00,482.519989,483.399994,478.880005,483.160004,22608700,0.00,0.0
2025-12-08 00:00:00-05:00,484.890015,492.299988,484.380005,491.019989,21965900,0.00,0.0
2025-12-09 00:00:00-05:00,489.100006,492.119995,488.500000,492.019989,14696100,0.00,0.0
2025-12-10 00:00:00-05:00,484.029999,484.250000,475.079987,478.559998,35756200,0.00,0.0
2025-12-11 00:00:00-05:00,476.630005,486.029999,475.859985,483.470001,24645000,0.00,0.0

In [8]:
# for multiple tickers , with spaces to seperate each
Tickers = yf.Tickers('MSFT AAPL GOOG')

In [ ]:
# to download 

yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo')

/tmp/ipykernel_6911/3944972606.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo')
[*********************100%***********************]  3 of 3 completed

Price            Close                                High              \
Ticker            AAPL        GOOG        MSFT        AAPL        GOOG
Date
2025-11-12  273.470001  287.242584  510.185150  275.730011  292.169362
2025-11-13  272.950012  278.938019  502.349792  276.700012  283.325171
2025-11-14  272.410004  276.799408  509.226898  275.959991  278.967976
2025-11-17  267.459991  285.413788  506.541931  270.489990  294.327955
2025-11-18  267.440002  284.774200  492.867554  270.709991  289.246289
2025-11-19  268.559998  292.798950  486.209991  272.209991  304.051618
2025-11-20  266.250000  289.790955  478.429993  275.429993  306.689934
2025-11-21  271.489990  299.454620  472.119995  273.329987  303.761808
2025-11-24  275.920013  318.262360  474.000000  277.000000  319.591479
2025-11-25  276.970001  323.428986  476.989990  280.380005  328.455705
2025-11-26  277.549988  320.071167  485.500000  279.529999  324.778087
2025-11-28  278.850006  319.911285  492.010010  279.000000  326.666888
2025-12-01  283.100006  314.914520  486.739990  283.420013  319.421589
2025-12-02  286.190002  315.813934  490.000000  287.399994  318.392269
2025-12-03  284.149994  320.410950  477.730011  288.619995  321.830037
2025-12-04  280.700012  318.182434  480.839996  284.730011  322.888348
2025-12-05  278.779999  321.879974  483.160004  281.140015  323.618830
2025-12-08  277.890015  314.450012  491.019989  279.670013  321.230011
2025-12-09  277.179993  317.750000  492.019989  280.029999  318.709015
2025-12-10  278.779999  321.000000  478.559998  279.750000  321.869995
2025-12-11  278.029999  313.700012  483.470001  279.589996  321.989990

Price                          Low                                Open  \
Ticker            MSFT        AAPL        GOOG        MSFT        AAPL
Date
2025-11-12  510.714159  271.700012  284.194585  498.187585  275.000000
2025-11-13  512.540710  272.089996  277.818754  500.353529  274.109985
2025-11-14  510.644259  269.600006  271.233033  496.510708  271.049988
2025-11-17  511.163287  265.730011  284.044686  503.966764  268.820007
2025-11-18  502.040388  265.320007  278.828098  485.870639  269.989990
2025-11-19  494.264923  265.500000  287.482442  481.927997  265.529999
2025-11-20  493.570007  265.920013  288.981485  475.500000  270.829987
2025-11-21  478.920013  265.670013  294.168061  468.269989  265.950012
2025-11-24  476.899994  270.899994  309.198266  468.019989  270.899994
2025-11-25  479.149994  275.250000  317.608778  464.890015  275.269989
2025-11-26  488.309998  276.630005  316.993189  481.200012  276.959991
2025-11-28  492.630005  275.989990  316.733366  486.649994  277.260010
2025-12-01  489.859985  276.140015  313.775279  484.649994  278.010010
2025-12-02  493.500000  282.630005  314.015120  486.320007  283.000000
2025-12-03  484.239990  283.299988  314.075087  475.200012  286.200012
2025-12-04  481.320007  278.589996  315.384241  476.489990  284.100006
2025-12-05  483.399994  278.049988  319.771365  478.880005  280.540009
2025-12-08  492.299988  276.149994  311.910004  484.380005  278.130005
2025-12-09  492.119995  276.920013  312.619995  488.500000  278.160004
2025-12-10  484.250000  276.440002  315.399994  475.079987  277.750000
2025-12-11  486.029999  273.809998  309.880005  475.859985  279.100006

Price                                 Volume
Ticker            GOOG        MSFT      AAPL      GOOG      MSFT
Date
2025-11-12  291.894548  508.408446  48398000  16998800  26574900
2025-11-13  282.800489  509.356667  49602800  18060200  25273100
2025-11-14  271.717702  497.299241  47431300  18330500  28505700
2025-11-17  286.213254  507.500160  45018300  34286100  19092800
2025-11-18  288.296896  494.444589  45677300  29702200  33815100
2025-11-19  287.497417  489.184435  40424500  43123600  23245300
2025-11-20  304.541311  492.709991  45823600  34801400  26802500
2025-11-21  296.676434  478.500000  59030800  43670600  31769200
2025-11-24  310.807232  475.000000  65585800  55311800  34421000
2025-11-25  326.586898  474.070007  46914200  50899300  28019800
2025-11-26  320.570841  486.309998  33431400  29839600  25709100
2025-11-28  323.219125  487.600006  20135600  19695800  14386700
2025-12-01  317.267996  488.440002  46587700  28520600  23964000
2025-12-02  316.693365  486.720001  53669500  24668200  19562700
2025-12-03  315.823946  476.320007  43538700  32285100  34615100
2025-12-04  322.834398  479.760010  43989100  20831600  22318200
2025-12-05  319.791341  482.519989  47265800  15719900  22608700
2025-12-08  321.029999  484.890015  38211800  22006900  21965900
2025-12-09  313.100006  489.100006  32193300  14151300  14696100
2025-12-10  316.619995  484.029999  33038300  22764500  35756200
2025-12-11  321.100006  476.630005  33207600  25856600  24645000